backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "clases"
    label: "clases Regulares"
    folder: "src/pages/escuela/clases"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "programa-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Profesora del Programa",
          name: "profesora",
          widget: "relation",
          collection: "profesoras",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - {
          label: "Tarifa",
          name: "tarifa",
          widget: "relation",
          multiple: true,
          collection: "tarifas",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title", "price"],
        }
      - {
          label: "Horarios",
          name: "horarios",
          widget: "relation",
          multiple: true,
          collection: "horarios",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - {
          label: "Dias",
          name: "dias",
          widget: "relation",
          multiple: true,
          collection: "dias",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - { label: "Estilo", name: "estilo", widget: "list" }
      - {
          label: "Nível del Programa",
          name: "nivel",
          multiple: true,
          widget: "select",
          options: ["Iniciación", "Intermedio", "Avanzado"],
        }

  - name: "online"
    label: "Escuela Online"
    folder: "src/pages/escuela/escuela-online"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "online-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Profesora del Programa",
          name: "profesora",
          widget: "relation",
          collection: "profesoras",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - {
          label: "Tarifa",
          name: "tarifa",
          widget: "relation",
          multiple: true,
          collection: "tarifas",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title", "price"],
        }
      - {
          label: "Horarios",
          name: "horarios",
          widget: "relation",
          multiple: true,
          collection: "horarios",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - {
          label: "Dias",
          name: "dias",
          widget: "relation",
          multiple: true,
          collection: "dias",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - { label: "Estilo", name: "estilo", widget: "list" }
      - {
          label: "Nível del Programa",
          name: "nivel",
          multiple: true,
          widget: "select",
          options: ["Iniciación", "Intermedio", "Avanzado"],
        }

  - name: "proyetos"
    label: "Proyetos"
    folder: "src/pages/escuela/proyetos"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "proyeto-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Tarifa",
          name: "tarifa",
          widget: "relation",
          multiple: true,
          collection: "tarifas",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title", "price"],
        }

  - name: "profesoras"
    label: "Profesores"
    folder: "src/pages/escuela/equipo"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "profesora-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "tarifas"
    label: "Tarifas"
    folder: "src/pages/escuela/tarifas"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "tarifa-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Publish Date", name: "date", widget: "datetime" }

  - name: "horarios"
    label: "Horarios"
    folder: "src/pages/escuela/horarios"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "horario-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }

  - name: "dias"
    label: "Dias"
    folder: "src/pages/escuela/dias"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "dias-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }

  - name: "salas"
    label: "Salas"
    folder: "src/pages/alquiler/salas"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "salas-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Pagina Inicial"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Description, name: description, widget: string }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about/centro.md"
        label: "El Centro"
        name: "centro"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about/filosofia.md"
        label: "Filosofia"
        name: "filosofia"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/alquiler/salas.md"
        label: "Salas"
        name: "salas-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "salas-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
